// ─────────────────────────────────────────────
//  AKATHTHI FARMS — RECIPE REGISTRY
//  To add a recipe: add one object here, drop
//  the HTML in the matching cuisine folder.
//  section: "grid" | "chef" | "customer"
// ─────────────────────────────────────────────

const RECIPES = [

  // ── SOUTH INDIAN ──────────────────────────
  {
    id: "kalan-milagu-varuval",
    title: "Kalan Milagu Varuval",
    subtitle: "Mushroom Pepper Fry",
    cuisine: "south-indian",
    cuisineLabel: "South Indian",
    variety: ["grey","elm"],
    varietyLabel: "Grey Oyster / Elm Oyster",
    time: 20,
    difficulty: "Easy",
    serves: 2,
    desc: "Black pepper, fennel, curry leaves, and torn oyster mushrooms roasted until the edges caramelise and the spices bloom dry. No water, no shortcuts. A weeknight dish that tastes like it took all afternoon.",
    img: "recipes/images/south-indian/milagu-varuval.jpg",
    imgCredit: "Kannamma Cooks",
    imgFallback: "linear-gradient(135deg,#4A2808 0%,#1B3F20 100%)",
    file: "recipes/south-indian/kalan-milagu-varuval.html",
    section: "grid",
    tags: ["quick","dry","spicy"]
  },
  {
    id: "chettinad-kulambu",
    title: "Chettinad Kalan Kulambu",
    subtitle: "Mushroom Chettinad Gravy",
    cuisine: "south-indian",
    cuisineLabel: "South Indian",
    variety: ["elm","grey"],
    varietyLabel: "Elm Oyster / Grey Oyster",
    time: 40,
    difficulty: "Medium",
    serves: 4,
    desc: "Stone-ground kalpasi, marathi mokku, and dried Guntur chillies build a thick brick-red kulambu that oyster mushrooms absorb like country chicken. Serve with parotta or idiyappam.",
    img: "recipes/images/south-indian/chettinad-kulambu.jpg",
    imgCredit: "Kannamma Cooks",
    imgFallback: "linear-gradient(135deg,#7A1A08 0%,#2E1408 100%)",
    file: "recipes/south-indian/chettinad-kulambu.html",
    section: "grid",
    tags: ["curry","spicy","weekend"]
  },
  {
    id: "kalan-thoran",
    title: "Kalan Thoran",
    subtitle: "Mushroom Coconut Stir-Fry",
    cuisine: "south-indian",
    cuisineLabel: "South Indian",
    variety: ["pink","golden"],
    varietyLabel: "Pink Oyster / Golden Oyster",
    time: 15,
    difficulty: "Easy",
    serves: 3,
    desc: "Fresh coconut, mustard seeds, green chilli, and turmeric — all in one pan, done in minutes. Pink oyster turns this humble thoran into something you'd find at a farm-table feast.",
    img: "recipes/images/south-indian/kalan-thoran.jpg",
    imgCredit: "Nish Kitchen",
    imgFallback: "linear-gradient(135deg,#C49A20 0%,#1B3F20 100%)",
    file: "recipes/south-indian/kalan-thoran.html",
    section: "grid",
    tags: ["quick","coconut","dry"]
  },
  {
    id: "mushroom-biryani",
    title: "Oyster Mushroom Dum Biryani",
    subtitle: "Chettinad-style Dum Biryani",
    cuisine: "south-indian",
    cuisineLabel: "South Indian",
    variety: ["elm","grey"],
    varietyLabel: "Elm Oyster / Grey Oyster",
    time: 60,
    difficulty: "Medium",
    serves: 4,
    desc: "Basmati layered with saffron, caramelised onions, whole spices, and thick oyster mushroom clusters — sealed and slow-cooked on dum. The mushrooms absorb the spice-laced steam and emerge fragrant through to the centre.",
    img: "recipes/images/south-indian/mushroom-biryani.jpg",
    imgCredit: "Swasthi's Recipes",
    imgFallback: "linear-gradient(135deg,#C49A20 0%,#3A2008 100%)",
    file: "recipes/south-indian/mushroom-biryani.html",
    section: "grid",
    tags: ["rice","weekend","celebration"]
  },

  // ── NORTH INDIAN ──────────────────────────
  {
    id: "kadai-mushroom",
    title: "Kadai Kalan",
    subtitle: "Kadai Mushroom",
    cuisine: "north-indian",
    cuisineLabel: "North Indian",
    variety: ["grey","elm"],
    varietyLabel: "Grey Oyster / Elm Oyster",
    time: 30,
    difficulty: "Easy",
    serves: 3,
    desc: "Freshly ground kadai masala — coriander, dried chilli, cloves — hits a screaming wok with onion and capsicum before torn oyster clusters get tossed in. The charred edges and silky mushroom texture are worth the smoke.",
    img: "recipes/images/north-indian/kadai-mushroom.jpg",
    imgCredit: "Veg Recipes of India",
    imgFallback: "linear-gradient(135deg,#C04A18 0%,#3A1008 100%)",
    file: "recipes/north-indian/kadai-mushroom.html",
    section: "grid",
    tags: ["curry","spicy","quick"]
  },
  {
    id: "matar-kalan",
    title: "Matar Kalan",
    subtitle: "Mushroom and Pea Masala",
    cuisine: "north-indian",
    cuisineLabel: "North Indian",
    variety: ["elm"],
    varietyLabel: "Elm Oyster",
    time: 30,
    difficulty: "Easy",
    serves: 4,
    desc: "Tomato-onion masala thickened with cashew paste, sweet green peas, and whole oyster clusters simmered until the gravy clings to everything. Enough body for butter naan or basmati.",
    img: "recipes/images/north-indian/matar-kalan.jpg",
    imgCredit: "Veg Recipes of India",
    imgFallback: "linear-gradient(135deg,#2E6636 0%,#1B3F20 100%)",
    file: "recipes/north-indian/matar-kalan.html",
    section: "grid",
    tags: ["curry","comfort","quick"]
  },

  // ── INDO-CHINESE ──────────────────────────
  {
    id: "mushroom-manchurian",
    title: "Mushroom Manchurian",
    subtitle: "Indo-Chinese Classic",
    cuisine: "indo-chinese",
    cuisineLabel: "Indo-Chinese",
    variety: ["elm","grey"],
    varietyLabel: "Elm Oyster / Grey Oyster",
    time: 30,
    difficulty: "Medium",
    serves: 3,
    desc: "Large torn clusters battered in seasoned corn flour, fried shatter-crisp, then tossed in a soy-ginger-garlic manchurian sauce that's sticky, sharp, and savoury. The mushroom's natural umami makes meat unnecessary.",
    img: "recipes/images/indo-chinese/mushroom-manchurian.jpg",
    imgCredit: "Swasthi's Recipes",
    imgFallback: "linear-gradient(135deg,#8A2208 0%,#1C1008 100%)",
    file: "recipes/indo-chinese/mushroom-manchurian.html",
    section: "grid",
    tags: ["fried","street-food","crowd-pleaser"]
  },
  {
    id: "hakka-noodles",
    title: "Oyster Mushroom Hakka Noodles",
    subtitle: "Wok-tossed Indo-Chinese",
    cuisine: "indo-chinese",
    cuisineLabel: "Indo-Chinese",
    variety: ["pink"],
    varietyLabel: "Pink Oyster",
    time: 20,
    difficulty: "Easy",
    serves: 2,
    desc: "High-heat wok, soy, vinegar, julienned vegetables — pink oyster mushrooms shred into silky ribbons that wind through the noodles like a red thread. Fast, loud-flavoured, exactly what you want at 9 PM.",
    img: "recipes/images/indo-chinese/hakka-noodles.jpg",
    imgCredit: "Sangs Kitchen",
    imgFallback: "linear-gradient(135deg,#B04428 0%,#1C1008 100%)",
    file: "recipes/indo-chinese/hakka-noodles.html",
    section: "grid",
    tags: ["quick","noodles","street-food"]
  },
  {
    id: "mushroom-fried-rice",
    title: "Oyster Mushroom Fried Rice",
    subtitle: "Wok-tossed Indo-Chinese",
    cuisine: "indo-chinese",
    cuisineLabel: "Indo-Chinese",
    variety: ["golden","grey"],
    varietyLabel: "Golden Oyster / Grey Oyster",
    time: 20,
    difficulty: "Easy",
    serves: 2,
    desc: "Day-old basmati, a ripping-hot wok, soy, spring onion, and golden oyster clusters that caramelise before the rice touches the pan. The mushrooms' subtle sweetness lifts this beyond standard fried rice.",
    img: "recipes/images/indo-chinese/mushroom-fried-rice.jpg",
    imgCredit: "Sangs Kitchen",
    imgFallback: "linear-gradient(135deg,#C49A20 0%,#1C1008 100%)",
    file: "recipes/indo-chinese/mushroom-fried-rice.html",
    section: "grid",
    tags: ["quick","rice","easy"]
  },

  // ── CONTINENTAL ───────────────────────────
  {
    id: "mushroom-steak",
    title: "Pan-Pressed Oyster Mushroom Steak",
    subtitle: "Continental",
    cuisine: "continental",
    cuisineLabel: "Continental",
    variety: ["elm","grey"],
    varietyLabel: "Elm Oyster / Grey Oyster",
    time: 25,
    difficulty: "Medium",
    serves: 2,
    desc: "A whole cluster pressed between two cast-iron pans, seared until crackling, then basted with garlic-thyme butter. With roasted potatoes and peppercorn sauce — the dish that stops people asking where the meat is.",
    img: "recipes/images/continental/mushroom-steak.jpg",
    imgCredit: "Yuzu Bakes",
    imgFallback: "linear-gradient(135deg,#4A3020 0%,#1B1008 100%)",
    file: "recipes/continental/mushroom-steak.html",
    section: "grid",
    tags: ["showstopper","weekend","cast-iron"]
  },
  {
    id: "creamy-pasta",
    title: "Creamy Oyster Mushroom Pasta",
    subtitle: "Continental",
    cuisine: "continental",
    cuisineLabel: "Continental",
    variety: ["golden","pink"],
    varietyLabel: "Golden Oyster / Pink Oyster",
    time: 20,
    difficulty: "Easy",
    serves: 2,
    desc: "Torn oyster clusters sautéed until golden, finished in a cream and garlic sauce that coats pasta with the weight you'd normally only get from a long-cooked ragu. Twenty minutes. Restaurant depth.",
    img: "recipes/images/continental/creamy-pasta.jpg",
    imgCredit: "Give Recipe",
    imgFallback: "linear-gradient(135deg,#C4A840 0%,#3A2A10 100%)",
    file: "recipes/continental/creamy-pasta.html",
    section: "grid",
    tags: ["quick","pasta","comfort"]
  },
  {
    id: "mushroom-toast",
    title: "Crispy Oyster Mushroom Toast",
    subtitle: "Café-style Brunch",
    cuisine: "continental",
    cuisineLabel: "Continental",
    variety: ["pink"],
    varietyLabel: "Pink Oyster",
    time: 15,
    difficulty: "Easy",
    serves: 2,
    desc: "Sourdough grilled in olive oil, spread with labneh, piled with roasted pink oyster mushrooms crisped at their frilled edges. Chilli flakes, herb oil, a squeeze of lemon. The dish dominating café menus from Melbourne to Mumbai.",
    img: "recipes/images/continental/mushroom-toast.jpg",
    imgCredit: "Brooke Kelly Nutrition",
    imgFallback: "linear-gradient(135deg,#C04060 0%,#3A1020 100%)",
    file: "recipes/continental/mushroom-toast.html",
    section: "grid",
    tags: ["quick","brunch","trending"]
  },

  // ── JAPANESE / KOREAN ─────────────────────
  {
    id: "mushroom-ramen",
    title: "Oyster Mushroom Miso Ramen",
    subtitle: "Japanese",
    cuisine: "japanese-korean",
    cuisineLabel: "Japanese / Korean",
    variety: ["grey","elm"],
    varietyLabel: "Grey Oyster / Elm Oyster",
    time: 40,
    difficulty: "Medium",
    serves: 2,
    desc: "Grey oysters carry deep umami that builds the broth from the inside. A tare of white miso and soy, soft-boiled egg, nori, spring onion. A bowl that earns its warmth.",
    img: "recipes/images/japanese-korean/mushroom-ramen.jpg",
    imgCredit: "Just One Cookbook",
    imgFallback: "linear-gradient(135deg,#3A3A4A 0%,#101018 100%)",
    file: "recipes/japanese-korean/mushroom-ramen.html",
    section: "grid",
    tags: ["soup","umami","weekend"]
  },
  {
    id: "doenjang-jjigae",
    title: "Doenjang Kalan Jjigae",
    subtitle: "Korean Fermented Soybean Stew",
    cuisine: "japanese-korean",
    cuisineLabel: "Japanese / Korean",
    variety: ["grey","elm"],
    varietyLabel: "Grey Oyster / Elm Oyster",
    time: 30,
    difficulty: "Easy",
    serves: 2,
    desc: "Korean fermented soybean paste, tofu, zucchini, and oyster mushrooms simmered in anchovy stock — earthy, funky, deeply restorative. The soup that Koreans have been eating for centuries and Chennai is just discovering.",
    img: "recipes/images/japanese-korean/doenjang-jjigae.jpg",
    imgCredit: "Maangchi",
    imgFallback: "linear-gradient(135deg,#5A3A18 0%,#1C1008 100%)",
    file: "recipes/japanese-korean/doenjang-jjigae.html",
    section: "grid",
    tags: ["soup","fermented","comfort"]
  },
  {
    id: "mushroom-onigiri",
    title: "Oyster Mushroom Onigiri",
    subtitle: "Japanese Rice Balls",
    cuisine: "japanese-korean",
    cuisineLabel: "Japanese / Korean",
    variety: ["golden","grey"],
    varietyLabel: "Golden Oyster / Grey Oyster",
    time: 25,
    difficulty: "Easy",
    serves: 4,
    desc: "Soy-glazed golden oyster mushrooms folded into seasoned Japanese rice, shaped into triangles, wrapped in nori. A portable, perfectly-balanced lunch that's become a fixture at Chennai's artisan food markets.",
    img: "recipes/images/japanese-korean/mushroom-onigiri.jpg",
    imgCredit: "Just One Cookbook",
    imgFallback: "linear-gradient(135deg,#2E6636 0%,#0C1408 100%)",
    file: "recipes/japanese-korean/mushroom-onigiri.html",
    section: "grid",
    tags: ["quick","portable","trending"]
  },

  // ── ROLLS / GRILLS / BBQ ──────────────────
  {
    id: "mushroom-kati-roll",
    title: "Oyster Mushroom Kati Roll",
    subtitle: "Street-style Wrap",
    cuisine: "rolls-grills-bbq",
    cuisineLabel: "Rolls & Grills",
    variety: ["elm","grey"],
    varietyLabel: "Elm Oyster / Grey Oyster",
    time: 20,
    difficulty: "Easy",
    serves: 2,
    desc: "Spiced oyster mushrooms pan-roasted with onion and green chilli, rolled in a soft paratha with raw onion, chaat masala, and green chutney. Street food that eats like a meal.",
    img: "recipes/images/rolls-grills-bbq/kati-roll.jpg",
    imgCredit: "Archana's Kitchen",
    imgFallback: "linear-gradient(135deg,#C49A20 0%,#3A2A08 100%)",
    file: "recipes/rolls-grills-bbq/mushroom-kati-roll.html",
    section: "grid",
    tags: ["quick","street-food","wrap"]
  },
  {
    id: "bbq-oyster-skewers",
    title: "BBQ Oyster Mushroom Skewers",
    subtitle: "Grilled with Smoky Glaze",
    cuisine: "rolls-grills-bbq",
    cuisineLabel: "Rolls & Grills",
    variety: ["elm","pink"],
    varietyLabel: "Elm Oyster / Pink Oyster",
    time: 25,
    difficulty: "Easy",
    serves: 4,
    desc: "Whole oyster clusters threaded on skewers, brushed with a tamarind-chilli-soy glaze, and grilled over high heat until the edges char and the glaze lacquers. A natural fit for terrace evenings and barbecue spreads.",
    img: "recipes/images/rolls-grills-bbq/bbq-skewers.jpg",
    imgCredit: "Minimalist Baker",
    imgFallback: "linear-gradient(135deg,#8A3A08 0%,#1C0808 100%)",
    file: "recipes/rolls-grills-bbq/bbq-oyster-skewers.html",
    section: "grid",
    tags: ["grill","bbq","outdoor"]
  },
  {
    id: "stuffed-mushroom-caps",
    title: "Stuffed Oyster Mushroom Caps",
    subtitle: "Baked with Herb Filling",
    cuisine: "rolls-grills-bbq",
    cuisineLabel: "Rolls & Grills",
    variety: ["elm"],
    varietyLabel: "Elm Oyster",
    time: 30,
    difficulty: "Medium",
    serves: 4,
    desc: "Large elm oyster caps filled with a mixture of breadcrumbs, caramelised onion, fresh herbs, and a touch of cream cheese — baked until golden and bubbling. An appetiser that disappears before you've finished plating.",
    img: "recipes/images/rolls-grills-bbq/stuffed-caps.jpg",
    imgCredit: "Downshiftology",
    imgFallback: "linear-gradient(135deg,#4A7C59 0%,#1B3F20 100%)",
    file: "recipes/rolls-grills-bbq/stuffed-mushroom-caps.html",
    section: "grid",
    tags: ["baked","appetiser","entertaining"]
  },

  // ── CHEF SPECIALS ─────────────────────────
  {
    id: "chef-chettinad-tasting",
    title: "Chettinad Mushroom Tasting Plate",
    subtitle: "Chef Arun — Akaththi Kitchen",
    cuisine: "chef-specials",
    cuisineLabel: "Chef Special",
    variety: ["elm","grey","golden"],
    varietyLabel: "All Three Varieties",
    time: 50,
    difficulty: "Advanced",
    serves: 2,
    desc: "Three oyster varieties, three Chettinad preparations — varuval, kulambu, and thoran — plated together to show how the same kitchen can draw entirely different characters from the same genus.",
    img: "recipes/images/chef-specials/chettinad-tasting.jpg",
    imgFallback: "linear-gradient(135deg,#7A1A08 0%,#1B3F20 100%)",
    file: "recipes/chef-specials/chettinad-tasting-plate.html",
    section: "chef",
    chef: "Arun",
    chefNote: "Oyster mushrooms have taught me to slow down my masala. The spice must bloom in the fat, not drown in water.",
    tags: ["tasting","chettinad","advanced"]
  },
  {
    id: "chef-mushroom-toast-special",
    title: "Wild Forest Toast",
    subtitle: "Chef Priya — Akaththi Kitchen",
    cuisine: "chef-specials",
    cuisineLabel: "Chef Special",
    variety: ["pink","golden"],
    varietyLabel: "Pink & Golden Oyster",
    time: 20,
    difficulty: "Medium",
    serves: 2,
    desc: "Multigrain sourdough, housemade curry-leaf labneh, roasted pink and golden oyster mushrooms, toasted black sesame, and a drizzle of cold-pressed coconut oil. Where Chennai meets the café table.",
    img: "recipes/images/chef-specials/wild-forest-toast.jpg",
    imgFallback: "linear-gradient(135deg,#C04060 0%,#C49A20 100%)",
    file: "recipes/chef-specials/wild-forest-toast.html",
    section: "chef",
    chef: "Priya",
    chefNote: "I wanted something that looked like it belonged on a brunch menu in London but tasted like home.",
    tags: ["brunch","trending","fusion"]
  },

  // ── CUSTOMER STORIES ──────────────────────
  {
    id: "customer-meera-thoran",
    title: "Amma's Thoran, Upgraded",
    subtitle: "Meera Krishnan — Adyar, Chennai",
    cuisine: "customer-stories",
    cuisineLabel: "Customer Story",
    variety: ["pink"],
    varietyLabel: "Pink Oyster",
    time: 15,
    difficulty: "Easy",
    serves: 3,
    desc: "My mother has been making thoran for 40 years. The first time I substituted Akaththi pink oyster, she didn't say a word — she just ate three helpings. That was enough.",
    img: "recipes/images/customer-stories/meera-thoran.jpg",
    imgFallback: "linear-gradient(135deg,#C49A20 0%,#1B3F20 100%)",
    file: "recipes/customer-stories/meera-thoran.html",
    section: "customer",
    customerName: "Meera Krishnan",
    customerLocation: "Adyar, Chennai",
    tags: ["thoran","quick","family"]
  },
  {
    id: "customer-rahul-ramen",
    title: "My Sunday Ramen Ritual",
    subtitle: "Rahul Sharma — Nungambakkam, Chennai",
    cuisine: "customer-stories",
    cuisineLabel: "Customer Story",
    variety: ["grey"],
    varietyLabel: "Grey Oyster",
    time: 45,
    difficulty: "Medium",
    serves: 2,
    desc: "I moved from Tokyo five years ago. For the longest time I couldn't find oyster mushrooms here that actually tasted like oyster mushrooms. Akaththi grey oyster changed that. My Sunday ramen ritual is back.",
    img: "recipes/images/customer-stories/rahul-ramen.jpg",
    imgFallback: "linear-gradient(135deg,#3A3A4A 0%,#101018 100%)",
    file: "recipes/customer-stories/rahul-ramen.html",
    section: "customer",
    customerName: "Rahul Sharma",
    customerLocation: "Nungambakkam, Chennai",
    tags: ["ramen","japanese","umami"]
  }

];

// Export for use in recipes.html
if (typeof module !== 'undefined') module.exports = RECIPES;
